### ISSUE TITLE
web.js: disconnect not finding open socket

### ISSUE THREAD

**Issue by MartinLoeper** [mia-z/capacitor-websocket#1]
Hey @mia-z, Thanks for this wonderful capacitor plugin!

I implemented it using the new web.js integration and found that the disconnect function is always failing: https://github.com/mia-z/capacitor-websocket/blob/main/src/web.ts#L80.

Do you have an idea why this might be the case and are you experiencing the same?

**Comment by mia-z** [comment]
Glad you're enjoying it!

I haven't extensively tested the web version since I mainly use the ios/android implementations. 

The only reason I could see it failing is if the socket is somehow null before the disconnect happens. Are you getting the error `Couldnt get socket with name: {name}` ?

**Comment by MartinLoeper** [comment]
Oh, no I am getting an error during disconnect: `Error: Tried to disconnect an already disconnected socket!`.

So the socket seems to exist inside the array but hasnt the connect flag set... which is strange because it still receives messages so it is definitely connected.

**Comment by MartinLoeper** [comment]
@mia-z Could it be that `this.sockets[t].socket.connected` is never set to true after socket connected?
