### ISSUE TITLE
Can you upgrade the dependency to 5.0.5

### ISSUE THREAD

**Issue by cneiu** [mia-z/capacitor-websocket#5]
Can you upgrade the dependency to 5.0.5

-----
"@capacitor/core": "5.0.5"

**Comment by newelement** [comment]
5.2.2 at this time

**Comment by mia-z** [comment]
Sorry for the long delay -- finally have some free time to dig into this. 

Have updated a lot of dependencies now, including the ones you mentioned. 
I had some Android build issues on mac, but it built fine in windows. Havent tested it much, so there may be further issues from all the dependency upgrades.
